orders = [
{"order_id": 1, "customer_name": "Arta", "city": "Vushtrri", "product": "Laptop", "category": "Electronics", "quantity": 1, "price": 700,
"status": "completed", "channel": "online", "order_date": "2026-07-01"},
{"order_id": 2, "customer_name": "Blend", "city": "Prishtina", "product": "Mouse", "category": "Accessories", "quantity": 2, "price": 15,
"status": "Completed", "channel": "store", "order_date": "2026-07-01"},
{"order_id": 3, "customer_name": "Arta", "city": "Vushtrri", "product": "Keyboard", "category": "Accessories", "quantity": 1, "price": 40,
"status": "cancelled", "channel": "online", "order_date": "2026-07-02"},
{"order_id": 4, "customer_name": "Dren", "city": "Mitrovica", "product": "Monitor", "category": "Electronics", "quantity": 1, "price":
180, "status": "completed", "channel": "store", "order_date": "2026-07-02"},
{"order_id": 5, "customer_name": "Elira", "city": "Prishtina", "product": "Mouse", "category": "accessories", "quantity": 1, "price": 15,
"status": "completed", "channel": "Online", "order_date": "2026-07-03"},
{"order_id": 6, "customer_name": "Dren", "city": "Mitrovica", "product": "Laptop", "category": "Electronics", "quantity": 1, "price": 700,
"status": "pending", "channel": "online", "order_date": "2026-07-03"},
{"order_id": 7, "customer_name": "Nora", "city": "Vushtrri", "product": "Headphones", "category": "Accessories", "quantity": 1, "price":
50, "status": "complete", "channel": "store", "order_date": "2026-07-04"},
{"order_id": 8, "customer_name": "Leart", "city": "Peja", "product": "Monitor", "category": "Electronics", "quantity": 2, "price": 180,
"status": "completed", "channel": "online", "order_date": "2026-07-04"},
{"order_id": 9, "customer_name": "Faton", "city": "Prizren", "product": "Desk Chair", "category": "Office", "quantity": 1, "price": 120,
"status": "completed", "channel": "store", "order_date": "2026-07-05"},
{"order_id": 10, "customer_name": "Gresa", "city": "Prishtina", "product": "USB Cable", "category": "Accessories", "quantity": 3, "price":
8, "status": "completed", "channel": "online", "order_date": "2026-07-05"},
{"order_id": 11, "customer_name": "Rina", "city": "Vushtrri", "product": "Laptop", "category": "Electronics", "quantity": 1, "price": 650,
"status": "cancelled", "channel": "store", "order_date": "2026-07-06"},
{"order_id": 12, "customer_name": "Arben", "city": "Ferizaj", "product": "Desk", "category": "Office", "quantity": 1, "price": 220,
"status": "pending", "channel": "online", "order_date": "2026-07-06"},
{"order_id": 13, "customer_name": "Gresa", "city": "Prishtina", "product": "Mouse", "category": "Accessories", "quantity": 4, "price": 15,
"status": "completed", "channel": "store", "order_date": "2026-07-07"},
{"order_id": 14, "customer_name": "Elira", "city": "Prishtina", "product": "Headphones", "category": "Accessories", "quantity": 2,
"price": 50, "status": "returned", "channel": "online", "order_date": "2026-07-07"},
{"order_id": 15, "customer_name": "", "city": "Gjilan", "product": "Webcam", "category": "Accessories", "quantity": 1, "price": 75,
"status": "completed", "channel": "online", "order_date": "2026-07-08"},
{"order_id": 16, "customer_name": "Bleron", "city": "Prishtine", "product": "Laptop", "category": "Electronics", "quantity": 1, "price":
720, "status": "completed", "channel": "partner", "order_date": "2026-07-08"},
{"order_id": 17, "customer_name": "Medina", "city": "Vushtrri", "product": "Desk", "category": "Office", "quantity": 0, "price": 220,
"status": "completed", "channel": "store", "order_date": "2026-07-09"},
{"order_id": 18, "customer_name": "Ilir", "city": "Mitrovica", "product": "Monitor", "category": "Electronics", "quantity": -1, "price":
180, "status": "completed", "channel": "online", "order_date": "2026-07-09"},
{"order_id": 19, "customer_name": "Isak", "city": "Peja", "product": "Office Lamp", "category": "Office", "quantity": 2, "price": 35,
"status": "Completed", "channel": "store", "order_date": "2026-07-10"},
{"order_id": 20, "customer_name": "Arta", "city": "Vushtrri", "product": "Laptop", "category": "Electronics", "quantity": 1, "price": 0,
"status": "completed", "channel": "online", "order_date": "2026-07-10"},
{"order_id": 21, "customer_name": "Leart", "city": "Peja", "product": "Keyboard", "category": "Accessories", "quantity": 2, "price": 40,
"status": "completed", "channel": "partner", "order_date": "2026-07-11"},
{"order_id": 22, "customer_name": "Nora", "city": "Vushtrri", "product": "Mouse", "category": "Accessories", "quantity": 1, "price": 15,
"status": "cancelled", "channel": "online", "order_date": "2026-07-11"},
{"order_id": 23, "customer_name": "Faton", "city": "Prizren", "product": "Desk Chair", "category": "Office", "quantity": 2, "price": 120,
"status": "completed", "channel": "store", "order_date": "2026-07-12"},
{"order_id": 24, "customer_name": "Rina", "city": "Vushtrri", "product": "USB Cable", "category": "Accessories", "quantity": 5, "price":
8, "status": "completed", "channel": "unknown", "order_date": "2026-07-12"},
]