-- Fixed Query 1
-- Fix: Joined the customers table because city is stored there.
-- Business: Shows how many orders come from each city.
SELECT customers.city, COUNT(*) AS order_count
FROM orders
JOIN customers
ON orders.customer_id = customers.customer_id
GROUP BY customers.city;

-- Fixed Query 2
-- Fix: Joined the products table to access product_name and price.
-- Business: Shows the total revenue generated by each completed product.
SELECT product_name, SUM(quantity * price) AS revenue
FROM orders
JOIN products
ON orders.product_id = products.product_id
WHERE status = 'completed'
GROUP BY product_name;

-- Fixed Query 3
-- Fix: Removed the semicolon after GROUP BY so the query continues to ORDER BY.
-- Business: Shows the number of orders for each status, sorted by the highest count.
SELECT status, COUNT(*) AS order_count
FROM orders
GROUP BY status
ORDER BY order_count DESC;

-- Fixed Query 4
-- Fix: Joined the products table to get the product price.
-- Business: Shows each order with its quantity, price, and total amount.
SELECT orders.order_id,
       orders.quantity,
       products.price,
       orders.quantity * products.price AS total_amount
FROM orders
JOIN products
ON orders.product_id = products.product_id;

-- Fixed Query 5
-- Fix: Joined the products table to get the category.
-- Business: Shows the total quantity sold for each category.
SELECT products.category, SUM(orders.quantity) AS total_quantity
FROM orders
JOIN products
ON orders.product_id = products.product_id
WHERE orders.status = 'completed'
GROUP BY products.category;

-- Fixed Query 6
-- No fix needed. The query is correct.
-- Business: Shows the total revenue from all orders.
SELECT SUM(quantity * price) AS total_revenue
FROM orders
JOIN products ON orders.product_id = products.product_id;

-- Fixed Query 7
-- Fix: Moved GROUP BY before HAVING.
-- Business: Shows customers who placed more than one order.
SELECT customer_id, COUNT(*) AS order_count
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 1;

-- Fixed Query 8
-- Fix: Added the ON clause to join the tables.
-- Business: Shows each order with the customer's name.
SELECT orders.order_id, customers.customer_name
FROM orders
JOIN customers
ON orders.customer_id = customers.customer_id;

-- Fixed Query 9
-- Fix: Specified the table for product_id.
-- Business: Shows the customer, product, and product price.
SELECT orders.customer_id, orders.product_id, products.price
FROM orders
JOIN products
ON orders.product_id = products.product_id;


-- Fixed Query 10
-- Fix: Changed the condition to exclude completed orders.
-- Business: Shows orders that do not count as revenue.
SELECT *
FROM orders
WHERE status != 'completed';